services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka-broker:
    image: bitnami/kafka:latest
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  data-ingestion:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.data_ingestion
    container_name: data-ingestion
    volumes:
      - ./data:/app/data
    depends_on:
      - kafka-broker

  data-preparation:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.data_preparation
    container_name: data-preparation
    volumes:
      - ./data:/app/data
    depends_on:
      - data-ingestion

  training:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.training
    container_name: training
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    depends_on:
      - data-preparation

  evaluation:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.evaluation
    container_name: evaluation
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    depends_on:
      - training

  deployment:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.deployment
    container_name: deployment
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
    depends_on:
      - evaluation

  monitoring:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.monitoring
    container_name: monitoring
    ports:
      - "5001:5001"
    volumes:
      - ./models:/app/models
    depends_on:
      - deployment

  retraining:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.retraining
    container_name: retraining
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    depends_on:
      - monitoring