# Dockerfile para el pipeline de entrenamiento

# Usar una imagen oficial de Python como base
FROM python:3.9-slim

# Establecer el directorio de trabajo en /app
WORKDIR /app

# Copiar el archivo requirements.txt y luego instalar las dependencias
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código de la aplicación
COPY . .

# Comando para ejecutar el script de entrenamiento
CMD ["python", "training_pipeline.py"]