apiVersion: batch/v1
kind: Job
metadata:
  name: model-monitoring-job
spec:
  template:
    spec:
      containers:
      - name: model-monitoring
        image: gcr.io/[PROJECT_ID]/model_monitoring:[TAG]
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
      env:
      - name: MONITORING_INTERVAL
        value: "86400"
      restartPolicy: Never
  backoffLimit: 3