apiVersion: batch/v1
kind: Job
metadata:
  name: model-retraining-job
spec:
  template:
    spec:
      containers:
      - name: model-retraining
        image: gcr.io/[PROJECT_ID]/model_retraining:[TAG]
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
      env:
      - name: DATA_PATH
        value: "data/new_transactions.csv"
      - name: MODEL_OUTPUT_PATH
        value: "models/fraud_detection_model_retrained.keras"
      restartPolicy: Never
  backoffLimit: 3